apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hostnic-node
rules:
  - apiGroups: [""]
    resources:
      - pods
      - nodes
      - namespaces
    verbs: ["list", "watch", "get","update", "patch"]
  - apiGroups: ["extensions"]
    resources:
      - daemonsets
    verbs: ["list", "watch"]
