apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hostnic-node
spec:
  template:
    spec:
      initContainers:
        - image: kubesphere/hostnic:latest
          name: hostnic-init
          imagePullPolicy: Always
      containers:
        # Change the value of image field below to your controller image URL
        - image: kubespheredev/hostnic:latest
          name: hostnic-node
          imagePullPolicy: Always
          command:
            - /bin/sh
          tty: true