apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hostnic-node
spec:
  template:
    spec:
      volumes:
        - name: nfs-test
          nfs:
            path: /mnt/sharedfolder/   #replace here
            server: 172.22.0.2    #replace here
      containers:
        - name: hostnic-node
          volumeMounts:
            - mountPath: /mnt/  #replace here
              name: nfs-test